#!/usr/bin/env bash
# Bash script that installs nginx on our ssh
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" > /var/www/html/index.html
