#!/usr/bin/env bash
# Bash script that installs nginx on our ssh
# safety measure
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
redirect="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n"
sudo sed -i "37i $redirect" /etc/nginx/sites-enabled/default
sudo service nginx restart
