#!/usr/bin/env bash
# Bash script that installs nginx on our ssh
# safety measure

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo sed -i "63 i\ \tadd_header X-Served-By $hostname;\n" /etc/nginx/sites-enabled/default
sudo service nginx start
