#!/usr/bin/env bash
# nginx must be running as nginx user
pkill apache2
sudo chmod 404 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
